# yaml-language-server: $schema=https://docs.overwire.io/schemas/modes.schema.json
defaultMode: mock
jobs:
  deprecated-commands: mock
steps:
  deprecated-commands.0: mock
  deprecated-commands.1: mock
  deprecated-commands.2: mock
  deprecated-commands.3: mock
  deprecated-commands.4: mock
