# yaml-language-server: $schema=https://docs.overwire.io/schemas/modes.schema.json
defaultMode: mock
jobs:
  build: mock
  security: mock
  audit: skip
  post-checks: mock
steps:
  post-checks.0: mock
  post-checks.1: mock
  post-checks.2: mock
