# yaml-language-server: $schema=https://docs.overwire.io/schemas/modes.schema.json
defaultMode: mock
jobs:
  evaluate: mock
steps:
  evaluate.0: mock
  evaluate.1: mock
  evaluate.2: mock
  evaluate.3: mock
  evaluate.4: mock
