# yaml-language-server: $schema=https://docs.overwire.io/schemas/modes.schema.json
defaultMode: mock
jobs:
  setup-preview: mock
  teardown-preview: mock
steps:
  setup-preview.0: mock
  setup-preview.1: mock
  teardown-preview.0: mock
  teardown-preview.1: mock
