# yaml-language-server: $schema=https://docs.overwire.io/schemas/modes.schema.json
defaultMode: mock
jobs:
  test: mock
steps:
  test.0: mock
  test.1: mock
  test.2: mock
  test.3: mock
  test.4: mock
