defaultMode: live
jobs:
  lint: live
  build: live
  test: live
  summary: live
steps:
  lint.0: live
  lint.1: live
  lint.2: live
  lint.3: live
  test.0: live
  test.1: live
  test.2: live
  test.3: live
  test.4: live
  summary.0: live
