# yaml-language-server: $schema=https://docs.overwire.io/schemas/modes.schema.json
defaultMode: live
jobs:
  gate: live
  deploy: live
  notify: live
steps:
  gate.0: live
  deploy.0: live
  deploy.1: live
  notify.0: live
  notify.1: live
