# yaml-language-server: $schema=https://docs.overwire.io/schemas/modes.schema.json
defaultMode: mock
jobs:
  integration: mock
steps:
  integration.0: mock
  integration.1: mock
  integration.2: mock
  integration.3: mock
  integration.4: mock
  integration.5: mock
  integration.6: mock
