# yaml-language-server: $schema=https://docs.overwire.io/schemas/modes.schema.json
defaultMode: mock
jobs:
  build: mock
steps:
  build.0: mock
  build.1: mock
  build.2: mock
  build.3: mock
  build.4: mock
  build.5: mock
  build.6: mock
  build.7: mock
