# yaml-language-server: $schema=https://docs.overwire.io/schemas/modes.schema.json
defaultMode: mock
jobs:
  build: mock
  verify: mock
steps:
  build.0: mock
  build.1: mock
  build.2: mock
  build.3: mock
  build.4: mock
  build.5: mock
  verify.0: mock
  verify.1: mock
  verify.2: mock
  verify.3: mock
