# yaml-language-server: $schema=https://docs.overwire.io/schemas/modes.schema.json
defaultMode: mock
jobs:
  lint: mock
steps:
  lint.0: mock
  lint.1: mock
  lint.2: mock
  lint.3: mock
  lint.4: mock
