# yaml-language-server: $schema=https://docs.overwire.io/schemas/modes.schema.json
defaultMode: live
jobs:
  check: live
steps:
  check.0: live
  check.1: live
  check.2: live
  check.3: live
  check.4: live
