# yaml-language-server: $schema=https://docs.overwire.io/schemas/modes.schema.json
defaultMode: live
jobs:
  build: live
  verify: live
steps:
  build.0: live
  build.1: live
  build.2: live
  build.3: live
  build.4: live
  build.5: live
  verify.0: live
  verify.1: live
  verify.2: live
  verify.3: live
