# yaml-language-server: $schema=https://docs.overwire.io/schemas/modes.schema.json
defaultMode: mock
jobs:
  audit: mock
steps:
  audit.0: live
  audit.1: live
  audit.2: live
  audit.3: live
  audit.4: live
