# yaml-language-server: $schema=https://docs.overwire.io/schemas/modes.schema.json
defaultMode: live
jobs:
  lint: live
steps:
  lint.0: live
  lint.1: live
  lint.2: live
  lint.3: live
  lint.4: live
