# yaml-language-server: $schema=https://docs.overwire.io/schemas/modes.schema.json
defaultMode: mock
jobs:
  check: mock
steps:
  check.0: mock
  check.1: mock
  check.2: mock
  check.3: mock
  check.4: mock
  check.5: mock
